---
- hosts: lamp-server
  become: true
  user: ec2-user
  roles:
    - common/hostname
    - common/timezone
    - common/selinux
    - common/swap
    - common/user_add
    - common/yum_update
    - httpd
    - php
    - mysql
