---
- name: remove mariadb
  dnf:
    name: mariadb-libs
    state: absent

- name: remove default mysql-community
  dnf:
    name: mysql-community-*
    state: absent

- name: install RPM-GPG-KEY-mysql
  rpm_key: 
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    state: present

- name: install repository for mysql-server
  shell: yum localinstall https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm -y

- name: disable mysql:8.0
  shell: dnf module disable mysql:8.0 -y

- name: install mysql8
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_items }}"

- name: install optional packages
  dnf:
    name:
      - expect
    state: present

- name: start mysql
  service:
    name: mysqld
    state: started
    enabled: yes

- name: copy my.cnf
  copy:
    src: ../templates/my.cnf
    dest: /etc
  notify:
    - restart mysqld