---
- name: install epel and remi
  dnf:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-8.rpm
    disable_gpg_check: yes

- name: install php
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_modules }}"

- name: copy php.ini
  copy:
    src: ../templates/php.ini
    dest: /etc