---
- name: install epel and remi
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    disable_gpg_check: yes

- name: Enable to install PHP.
  shell: "amazon-linux-extras enable php7.3"
  changed_when: False

- name: Install PHP.
  yum:
    name: "{{ item }}"
    enablerepo: amzn2extra-php7.3
    state: present
  with_items:
    - "{{ php_modules }}"

- name: copy php.ini
  copy:
    src: ../templates/php.ini
    dest: /etc